//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoBook.RestoBookServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Restaurants", Namespace="http://schemas.datacontract.org/2004/07/RestoBook.DataService")]
    [System.SerializableAttribute()]
    public partial class Restaurants : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuisineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VilleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CP {
            get {
                return this.CPField;
            }
            set {
                if ((object.ReferenceEquals(this.CPField, value) != true)) {
                    this.CPField = value;
                    this.RaisePropertyChanged("CP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cuisine {
            get {
                return this.CuisineField;
            }
            set {
                if ((object.ReferenceEquals(this.CuisineField, value) != true)) {
                    this.CuisineField = value;
                    this.RaisePropertyChanged("Cuisine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rue {
            get {
                return this.RueField;
            }
            set {
                if ((object.ReferenceEquals(this.RueField, value) != true)) {
                    this.RueField = value;
                    this.RaisePropertyChanged("Rue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ville {
            get {
                return this.VilleField;
            }
            set {
                if ((object.ReferenceEquals(this.VilleField, value) != true)) {
                    this.VilleField = value;
                    this.RaisePropertyChanged("Ville");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RestoBookServiceReference.IRestoBookRestaurantService")]
    public interface IRestoBookRestaurantService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestoBookRestaurantService/GetAllRestaurant", ReplyAction="http://tempuri.org/IRestoBookRestaurantService/GetAllRestaurantResponse")]
        RestoBook.RestoBookServiceReference.Restaurants[] GetAllRestaurant();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IRestoBookRestaurantService/GetAllRestaurant", ReplyAction="http://tempuri.org/IRestoBookRestaurantService/GetAllRestaurantResponse")]
        System.IAsyncResult BeginGetAllRestaurant(System.AsyncCallback callback, object asyncState);
        
        RestoBook.RestoBookServiceReference.Restaurants[] EndGetAllRestaurant(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestoBookRestaurantService/GetRestaurantByState", ReplyAction="http://tempuri.org/IRestoBookRestaurantService/GetRestaurantByStateResponse")]
        RestoBook.RestoBookServiceReference.Restaurants[] GetRestaurantByState(bool active);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IRestoBookRestaurantService/GetRestaurantByState", ReplyAction="http://tempuri.org/IRestoBookRestaurantService/GetRestaurantByStateResponse")]
        System.IAsyncResult BeginGetRestaurantByState(bool active, System.AsyncCallback callback, object asyncState);
        
        RestoBook.RestoBookServiceReference.Restaurants[] EndGetRestaurantByState(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRestoBookRestaurantServiceChannel : RestoBook.RestoBookServiceReference.IRestoBookRestaurantService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllRestaurantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllRestaurantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public RestoBook.RestoBookServiceReference.Restaurants[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((RestoBook.RestoBookServiceReference.Restaurants[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetRestaurantByStateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRestaurantByStateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public RestoBook.RestoBookServiceReference.Restaurants[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((RestoBook.RestoBookServiceReference.Restaurants[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestoBookRestaurantServiceClient : System.ServiceModel.ClientBase<RestoBook.RestoBookServiceReference.IRestoBookRestaurantService>, RestoBook.RestoBookServiceReference.IRestoBookRestaurantService {
        
        private BeginOperationDelegate onBeginGetAllRestaurantDelegate;
        
        private EndOperationDelegate onEndGetAllRestaurantDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllRestaurantCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetRestaurantByStateDelegate;
        
        private EndOperationDelegate onEndGetRestaurantByStateDelegate;
        
        private System.Threading.SendOrPostCallback onGetRestaurantByStateCompletedDelegate;
        
        public RestoBookRestaurantServiceClient() {
        }
        
        public RestoBookRestaurantServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestoBookRestaurantServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestoBookRestaurantServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestoBookRestaurantServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetAllRestaurantCompletedEventArgs> GetAllRestaurantCompleted;
        
        public event System.EventHandler<GetRestaurantByStateCompletedEventArgs> GetRestaurantByStateCompleted;
        
        public RestoBook.RestoBookServiceReference.Restaurants[] GetAllRestaurant() {
            return base.Channel.GetAllRestaurant();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAllRestaurant(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllRestaurant(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public RestoBook.RestoBookServiceReference.Restaurants[] EndGetAllRestaurant(System.IAsyncResult result) {
            return base.Channel.EndGetAllRestaurant(result);
        }
        
        private System.IAsyncResult OnBeginGetAllRestaurant(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetAllRestaurant(callback, asyncState);
        }
        
        private object[] OnEndGetAllRestaurant(System.IAsyncResult result) {
            RestoBook.RestoBookServiceReference.Restaurants[] retVal = this.EndGetAllRestaurant(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllRestaurantCompleted(object state) {
            if ((this.GetAllRestaurantCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllRestaurantCompleted(this, new GetAllRestaurantCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllRestaurantAsync() {
            this.GetAllRestaurantAsync(null);
        }
        
        public void GetAllRestaurantAsync(object userState) {
            if ((this.onBeginGetAllRestaurantDelegate == null)) {
                this.onBeginGetAllRestaurantDelegate = new BeginOperationDelegate(this.OnBeginGetAllRestaurant);
            }
            if ((this.onEndGetAllRestaurantDelegate == null)) {
                this.onEndGetAllRestaurantDelegate = new EndOperationDelegate(this.OnEndGetAllRestaurant);
            }
            if ((this.onGetAllRestaurantCompletedDelegate == null)) {
                this.onGetAllRestaurantCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllRestaurantCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllRestaurantDelegate, null, this.onEndGetAllRestaurantDelegate, this.onGetAllRestaurantCompletedDelegate, userState);
        }
        
        public RestoBook.RestoBookServiceReference.Restaurants[] GetRestaurantByState(bool active) {
            return base.Channel.GetRestaurantByState(active);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetRestaurantByState(bool active, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRestaurantByState(active, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public RestoBook.RestoBookServiceReference.Restaurants[] EndGetRestaurantByState(System.IAsyncResult result) {
            return base.Channel.EndGetRestaurantByState(result);
        }
        
        private System.IAsyncResult OnBeginGetRestaurantByState(object[] inValues, System.AsyncCallback callback, object asyncState) {
            bool active = ((bool)(inValues[0]));
            return this.BeginGetRestaurantByState(active, callback, asyncState);
        }
        
        private object[] OnEndGetRestaurantByState(System.IAsyncResult result) {
            RestoBook.RestoBookServiceReference.Restaurants[] retVal = this.EndGetRestaurantByState(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRestaurantByStateCompleted(object state) {
            if ((this.GetRestaurantByStateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRestaurantByStateCompleted(this, new GetRestaurantByStateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRestaurantByStateAsync(bool active) {
            this.GetRestaurantByStateAsync(active, null);
        }
        
        public void GetRestaurantByStateAsync(bool active, object userState) {
            if ((this.onBeginGetRestaurantByStateDelegate == null)) {
                this.onBeginGetRestaurantByStateDelegate = new BeginOperationDelegate(this.OnBeginGetRestaurantByState);
            }
            if ((this.onEndGetRestaurantByStateDelegate == null)) {
                this.onEndGetRestaurantByStateDelegate = new EndOperationDelegate(this.OnEndGetRestaurantByState);
            }
            if ((this.onGetRestaurantByStateCompletedDelegate == null)) {
                this.onGetRestaurantByStateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRestaurantByStateCompleted);
            }
            base.InvokeAsync(this.onBeginGetRestaurantByStateDelegate, new object[] {
                        active}, this.onEndGetRestaurantByStateDelegate, this.onGetRestaurantByStateCompletedDelegate, userState);
        }
    }
}
