//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoBook.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresse
    {
        public int Id { get; set; }
        public string lb_rue { get; set; }
        public string lb_codepostal { get; set; }
        public int VilleId { get; set; }
        public int RestaurantsId { get; set; }
    
        public virtual Restaurants Restaurants { get; set; }
        public virtual Ville Ville { get; set; }
    }
}
