//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoBook.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int Id_Picture { get; set; }
        public string lb_Name { get; set; }
        public byte[] lb_Picure { get; set; }
        public bool banner { get; set; }
        public int fk_Restaurant { get; set; }
    
        public virtual Restaurants Restaurants { get; set; }
    }
}
